config/routes.rb
Rails.application.routes.draw do

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]
  
  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end

  namespace :admin do
    resources :users, only: %i[index create]
  end
 

  root 'pages#index'
  
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  # def formatted_created_at
  #   created_at.strftime('%Y-%m-%d %H:%M:%S')
  # end
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # before_action :set_question!, only: %i[show destroy edit update]

  def show
    @question = Question.find(params[:id]).decorate
    # @question = @question.decorate
    @answer = @question.answers.build
    @answers = @question.answers.order(created_at: :desc).page(params[:page]).per(5).decorate
    # @answers = Answer.where(question: @question).limit(2).order(created_at: :desc)
    # @answers = @answers.decorate

  end

  def destroy
    @question = Question.find params[:id]
    @question.destroy
    flash[:success] = "Question deleted!"
    redirect_to questions_path
  end

  def edit
    @question = Question.find params[:id]
  end

  def update
    @question = Question.find params[:id]
     if @question.update question_params
      flash[:success] = "Question updated!"
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).decorate
    # @questions = @questions.decorate
  end
  
  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      flash[:success] = "Question created!"
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  # def set_question!
  #   @question = Question.find params[:id]
  # end

end

app/views/questions/_form.html.erb
  <%= render 'shared/errors', object: @question %>



<%= form_with model: @question do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>

    <div class="col-sm-10">
      <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>

  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit "Submit question", class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<% provide :page_title, 'Edit question' %>

<% currently_at 'Edit question' %>


<h1 class="mb-4">Edit question</h1>

  <%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>

<h1 class="mb-4">Questions</h1>

<%= link_to 'New question', new_question_path, class: 'btn btn-primary btn-lg' %>

<%= paginate(@questions) %>

<% @questions.each do |question| %>
  <article class="card mt-3">
    <div class="card-body">
      <h2><%= question.title %></h2>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
          <small><%= question.formatted_created_at %></small>
        </time>

        <p class="my-2">
          <%= truncate strip_tags(question.body), length: 120, omission: '... (continued)'%>
        </p>
      </section>

     
      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary' %>
       <%= link_to 'Destroy', question_path(question), class: 'btn btn-danger', data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>


    </div>
  </article>
 
<% end %>

<%= paginate @questions %>

app/views/questions/new.html.erb
<% provide :page_title, 'New question' %>

<% currently_at 'New question' %>

<h1 class="mb-4">New question</h1>


  <%= render 'form' %>

app/views/questions/show.html.erb
<% provide :page_title, 'Show question' %>

<% currently_at 'Show question' %>


<h1 class="mb-4"><%= @question.title %></h1>

<time datetime="<%= @question.formatted_created_at %>">
    <%= @question.formatted_created_at %>
</time>

<div class="lead my-3">
  <%= sanitize @question.body %><br>
</div>

<%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %>  
<%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary' %>
<%= link_to 'Destroy', question_path(@question), class: 'btn btn-danger',
  data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>


<hr class="my-3">

<h2>Write your answer</h2>

<%= render 'answers/form' %>

<h2 class="mt-5">Answers</h2>

<%= paginate @answers %>

<%= render partial: 'answers/answer', collection: @answers, as: :answer, locals: {question: @question} %>

<%= paginate @answers %>

     