config/routes.rb
Rails.application.routes.draw do

  resource :session, only: %i[new create destroy]

  resources :users, only: %i[new create edit update]
  
  resources :questions do
    resources :answers, only: %i[create destroy edit update]
  end

  namespace :admin do
    resources :users, only: %i[index create]
  end
 

  root 'pages#index'
  
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true, length: {minimum: 5}

  # def formatted_created_at
  #   created_at.strftime('%Y-%m-%d %H:%M:%S')
  # end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :set_question!
  # before_action :set_answer!, except: :create

  def edit
    @answer = @question.answers.find params[:id]
  end

  def update
    @answer = @question.answers.find params[:id]
    if @answer.update answer_params
      flash[:success] = "Answer updated!"
      redirect_to question_path(@question, anchor: "answer-#{@answer.id}")
    else
      render :edit
    end
  end

  def create
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = "Answer create!"
      redirect_to question_path(@question, anchor: "answer-#{@answer.id}")
    else
      @question = @question.decorate
      @answers = @question.answers.order created_at: :desc
      @answers = @answers.decorate
      render 'questions/show'
    end
  end

  def destroy
    answer = @question.answers.find params[:id]
    answer.destroy
    flash[:success] = "Answer deleted!"
    redirect_to questions_path
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find(params[:question_id])
  end

  # def set_answer!
  #   @answer = @question.answers.find params[:id]
  # end
  
end

app/views/answers/_answer.html.erb
  <article class="mb-3 card" id="answer-<%= answer.id %>">
    <div class="card-body">
      <section class="card-text">
        <small><time datetime="<%= answer.formatted_created_at %>">
          <%= answer.formatted_created_at %>
        </time></small>

        <div class="mt-2 mb-3">
          <%= sanitize answer.body %>
          <%= answer [:id] %>
        </div> 
      </section>

    <%= link_to 'Edit', edit_question_answer_path(question, answer), class: 'btn btn-secondary' %>
    <%= link_to 'Delete', question_answer_path(question, answer), class: 'btn btn-danger btn-sm',
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
  </article>

app/views/answers/_form.html.erb
<%= render 'shared/errors', object: @answer %>

<%= form_with model: [@question, @answer] do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :body %>
    </div>

    <div class="col-sm-10">
      <%= f.text_area :body, class: 'form-control', required: true %>
    </div>
  </div>

  <%= f.submit "Submit answer", class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% provide :page_title, 'Edit answeer' %>

<% currently_at 'Edit answer' %>


<h1 class="mb-4">Edit Answer</h1>


<%= render 'form' %>